#!/usr/bin/env python3
"""
sysml_trade.py -- cam pin x side plate trade study for the CINVA-Ram press.

Runs cinva_simple (full checks + collision sweep) for every combination in FACTORS,
caches each run in trade_cache.json (rerun skips finished variants), prints the table,
and emits CinvaRamTrade.sysml: one alternative per variant specializing cinvaRam, and a
TradeStudy (SysML v2 standard library) maximizing the minimum stress margin over the
feasible alternatives.

Usage (repo root):
    python3 sysml_trade.py [--no-sweep] [--limit 165]
"""
from __future__ import annotations

import argparse
import dataclasses
import itertools
import json
from pathlib import Path

import cinva_simple as cs

FACTORS = {                 # Params field -> (SysML attribute, levels)
    "d_cam":  ("dCam",  (1.250, 1.375, 1.500)),
    "t_side": ("tSide", (0.500, 0.625)),
}
CACHE = Path("trade_cache.json")


def vid(over: dict) -> str:
    return "v_" + "_".join(f"{k.replace('_', '')}{round(v * 1000)}" for k, v in over.items())


def evaluate(over: dict, sweep: bool) -> dict:
    p = dataclasses.replace(cs.Params(), **over)
    stress = cs.checks(p)
    func = cs.verify(p, sweep=sweep)
    interf = next((0 if ok else len(d.split("; ")) for n, ok, d in func if n.startswith("All positions")), 0)
    worst = min(stress, key=lambda r: r[3] / r[2])
    return dict(
        over=over, sweep=sweep,
        peak=p.peak_hand(), eject=cs.max_eject_hand(p),
        mass=sum(pt.weight(p) * pt.qty for pt in cs.parts(p)),
        min_margin=worst[3] / worst[2] - 1, worst=worst[0],
        margins={r[0]: r[3] / r[2] - 1 for r in stress},
        fails=[n for n, ok, _ in func if not ok], interf=interf,
    )


def emit(rows: list[dict], limit: float) -> str:
    L = []
    a = L.append
    a("/* GENERATED by sysml_trade.py -- do not hand-edit */")
    a("package CinvaRamTrade {")
    for imp in ("ScalarValues", "ISQ", "SI", "USCustomaryUnits", "TradeStudies", "CinvaRamExample"):
        a(f"    private import {imp}::*;")
    a("")
    for r in rows:
        a(f"    part {vid(r['over'])} :> cinvaRam {{")
        for k, v in r["over"].items():
            a(f"        :>> {FACTORS[k][0]} = {v:g} ['in'];")
        a(f"        :>> peakHandleForce = {r['peak']:.1f} [lbf];")
        a(f"        :>> peakEjectForce  = {r['eject']:.1f} [lbf];")
        a(f"        :>> steelMass       = {r['mass']:.1f} [lb];")
        a(f"        :>> minMargin       = {r['min_margin']:.4f};   // {r['worst']}")
        a(f"        :>> interferences   = {r['interf']};")
        a(f"        :>> functionalFails = {len(r['fails'])};")
        a("    }")
    a("")
    alts = ", ".join(vid(r["over"]) for r in rows)
    a("    analysis camPinTrade : TradeStudy {")
    a("        doc /* Maximize the minimum stress margin; infeasible alternatives score -1. */")
    a(f"        subject :>> studyAlternatives : CinvaRam[1..*] = ({alts});")
    a("        calc :>> evaluationFunction {")
    a("            in ref :>> alternative : CinvaRam;")
    a("            return attribute :>> result : Real =")
    a("                if alternative.interferences == 0 and alternative.functionalFails == 0 and")
    a(f"                   alternative.peakHandleForce <= {limit:g} [lbf]")
    a("                ? alternative.minMargin else -1.0;")
    a("        }")
    a("        objective :>> tradeStudyObjective : MaximizeObjective;")
    a("    }")
    a("}")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--no-sweep", action="store_true")
    ap.add_argument("--limit", type=float, default=165.0, help="handle force limit, lbf")
    a = ap.parse_args()
    sweep = not a.no_sweep

    cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
    keys = list(FACTORS)
    rows = []
    for combo in itertools.product(*(FACTORS[k][1] for k in keys)):
        over = dict(zip(keys, combo))
        k = vid(over)
        if k not in cache or cache[k]["sweep"] != sweep:
            print(f"running {k} ...", flush=True)
            cache[k] = evaluate(over, sweep)
            CACHE.write_text(json.dumps(cache, indent=1))
        rows.append(cache[k])

    feas = lambda r: not r["fails"] and r["interf"] == 0 and r["peak"] <= a.limit
    score = lambda r: r["min_margin"] if feas(r) else -1.0
    best = max(rows, key=score)
    print(f"\n{'variant':18s} {'margin':>7s}  {'worst check':28s} {'pull':>6s} {'eject':>6s} {'steel':>6s}  status")
    for r in sorted(rows, key=score, reverse=True):
        st = "OK" if feas(r) else ("FAIL " + ", ".join(r["fails"]) if r["fails"] else
                                  f"pull>{a.limit:g}" if r["peak"] > a.limit else "interf")
        mark = " <- best" if r is best else ""
        print(f"{vid(r['over']):18s} {r['min_margin']:+7.1%}  {r['worst']:28s} {r['peak']:6.1f} {r['eject']:6.1f} "
              f"{r['mass']:6.1f}  {st}{mark}")
    Path("CinvaRamTrade.sysml").write_text(emit(rows, a.limit))
    print("wrote CinvaRamTrade.sysml")


if __name__ == "__main__":
    main()
