(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var G0=function(a){a.V("cardstatechange",a.Hg()&&a.Ii()?1:0)},H0=function(a,b){var c=g.Ma(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},sEa=function(a){var b=g.wg(a);
a=g.Eg(a);return new g.cg(b.x,b.y,a.width,a.height)},tEa=function(a){return Math.pow(a,3)},uEa=function(a){return 3*a*a-2*a*a*a},K0=function(a){a=g.Pa(a);
delete I0[a];g.Pb(I0)&&J0&&J0.stop()},wEa=function(){J0||(J0=new g.M(function(){vEa()},20));
var a=J0;a.isActive()||a.start()},vEa=function(){var a=g.Sa();
g.Cb(I0,function(b){xEa(b,a)});
g.Pb(I0)||wEa()},L0=function(a,b,c,d){g.pn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.J=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.I=0;this.B=null},xEa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.I=1E3/(b-a.B);a.B=b;yEa(a,a.progress);1==a.progress?(a.Ma=0,K0(a),a.onFinish(),a.Cr()):a.Kb()&&a.qw()},yEa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.J[c]-a.i[c])*b+a.i[c]},zEa=function(a,b){g.Cl.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.I;this.state=b.Ma},M0=function(a,b,c,d,e){L0.call(this,b,c,d,e);
this.element=a},N0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
M0.call(this,a,b,c,d,e)},O0=function(a){g.E.call(this);
this.l=a||window;this.i=[]},P0=function(a){return a.baseUrl||null},Q0=function(a,b){return g.Ne(g.Qc(a,b,void 0),function(c){return!!c})},AEa=function(a,b,c){function d(T){var na,wa,Ka,Ua=T.hovercardButton;
if(!Ua)return null;Ua=Ua.subscribeButtonRenderer;if(!Ua)return null;var lc=f(Ua.unsubscribedButtonText),sb=f(Ua.subscribedButtonText);if(Ua.subscribed){var Zc=f(Ua.subscriberCountWithUnsubscribeText);var Sb=f(Ua.subscriberCountText)}else Zc=f(Ua.subscriberCountText),Sb=f(Ua.subscriberCountWithSubscribeText);var $b=null;return T.signinEndpoint&&($b=H0(T,"signinEndpoint","webNavigationEndpointData","url"),$b||($b=null===(Ka=null===(wa=null===(na=Ua.signInEndpoint)||void 0===na?void 0:na.commandMetadata)||
void 0===wa?void 0:wa.webCommandMetadata)||void 0===Ka?void 0:Ka.url),!$b)?null:lc&&(sb||$b)?{subscribed:Ua.subscribed,subscribeText:lc,subscribeCount:Zc,unsubscribeText:sb,unsubscribeCount:Sb,enabled:Ua.enabled,signinUrl:$b,classic:T.useClassicSubscribeButton}:null}
function e(T){if(T){var na=[],wa=T.videoId;wa&&na.push("v="+wa);(wa=T.playlistId)&&na.push("list="+wa);(T=T.startTimeSeconds)&&na.push("t="+T);return"/watch?"+na.join("&")}}
function f(T){if(!T)return null;var na=T.simpleText;return na?na:T.runs?g.Qc(T.runs,function(wa){return wa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,w=null,x=!1,y=null,F=null,D=null,G=null,K=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=H0(l,"browseEndpoint","browseId"))w=x,m="/channel/"+w;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):F=f(b.subscribersText)}else"WEBSITE"===
h?((D=H0(l,"urlEndpoint","url"))&&(m=D),n=!0,p="new",D=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(K=f(b.additionalFeesText)),(n=H0(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=H0(b,"title","accessibility","accessibilityData","label");var J=b.endpoint?b.endpoint.clickTrackingParams:null,H="";if(b.metadata){var L=f(b.metadata);L&&(H=L)}return{id:"element-"+c,type:h,title:f(b.title),metadata:H,callToAction:f(b.callToAction),gD:b.image,
iconUrl:D,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:w,subscribeButton:y,subscribersText:F,isSubscribe:x,targetUrl:m||null,VL:n,Cd:J?{itct:J}:null,CQ:p,bq:a?a:null,YL:b.isPlaceholder,impressionUrls:Q0(b.impressionUrls||[],P0),OL:Q0(b.hovercardShowUrls||[],P0),clickUrls:Q0(l.loggingUrls||[],P0),visualElement:g.cu(b.trackingParams),productPrice:G,
additionalFeesText:K}},R0=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:Q0(a.impressionUrls||[],P0),elements:Q0(a.elements||[],function(d,e){return AEa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.cu(a.trackingParams));return c},S0=function(a){g.eN.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.J=[];this.W=!0;this.I=0;a=a.T();this.L=g.VF(a)||g.YF(a);this.events=new g.XM(this);g.I(this,this.events);this.events.N(this.player,g.AD("creatorendscreen"),this.zd);this.events.N(this.player,g.BD("creatorendscreen"),this.mf);this.events.N(this.player,"resize",this.Ta);this.events.N(window,"focus",this.DP);this.load();var b=g.Ie("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Gi(this,function(){g.Me(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},BEa=function(a){return a.player.getVideoData().C?"current":a.L?"new":"current"},T0=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},CEa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=R0(f,BEa(a))));U0(a,f)},
urlParams:{v:c},withCredentials:!0};a.L&&(c.urlParams.ptype="embedded");var d=b.cm;d&&(c.postParams={ad_tracking:d});if(b=g.Iia(b))if(b=g.Lc(b),b=g.Hc(b))a.u=g.Tp(b,c)},U0=function(a,b,c){c=void 0===c?!0:c;
a.player.Oe("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&DEa(a);c=[];d=new g.xD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().i||(a.l=new g.X({D:"div",K:"ytp-ce-shadow"}),g.VM(a.player,a.l.element,4),a.B=new g.LL(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=EEa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.VM(a.player,f.element,4);var h=new g.xD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);FEa(a,f,e)}else g.ht(new g.Tr("buildEndscreenElement null",
e))}a.player.sd(c);a.Ta()}},DEa=function(a){var b=g.gu(),c=g.iu();
c&&b&&a.endscreen.visualElement&&g.wu(c,b,a.endscreen.visualElement)},EEa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={D:"div",ka:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.bq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:V0(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:W0(a,b.targetUrl),tabindex:"-1"},S:[{D:"div",ka:["ytp-ce-video-title"].concat(g.la(c)),U:{dir:g.vn(b.title||
"")},ba:b.title},{D:"div",K:"ytp-ce-video-duration",ba:b.videoDuration||void 0}]}]};c=new g.X(c);break;case "PLAYLIST":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={D:"div",ka:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.bq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:V0(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:W0(a,
b.targetUrl),tabindex:"-1"},S:[{D:"div",ka:["ytp-ce-playlist-title"].concat(g.la(c)),U:{dir:g.vn(b.title||"")},ba:b.title},{D:"div",K:"ytp-ce-playlist-count",S:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",ba:b.playlistLength||void 0}]}]}]};c=new g.X(c);break;case "CHANNEL":c={D:"div",ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.bq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},
{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"a",ka:["ytp-ce-channel-title","ytp-ce-link"],U:{href:W0(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.vn(b.title||"")},ba:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",S:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",ba:b.subscribersText}:"",b.metadata?{D:"div",ka:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],ba:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:V0(b)}]};c=new g.X(c);var d=g.se(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.N(d,"ytp-ce-subscribe-button");if(a.player.T().i){var e=null;var f=b.Cd.itct}else e="endscreen",f=null;e=new g.fO(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":c={D:"div",ka:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.bq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},
{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-website-title",U:{dir:g.vn(b.title||"")},ba:b.title},{D:"div",K:"ytp-ce-website-metadata",ba:b.metadata},{D:"a",ka:["ytp-ce-website-goto","ytp-ce-link"],U:{href:W0(a,b.targetUrl),target:"_blank",tabindex:"-1"},ba:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:V0(b)},{D:"div",
K:"ytp-ce-expanding-icon",U:GEa(b.iconUrl)}]};c=new g.X(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",S:[{D:"div",K:"ytp-ce-merchandise-price",ba:b.productPrice}]},b.additionalFeesText&&c.S.push({D:"div",K:"ytp-ce-merchandise-additional-fees",ba:b.additionalFeesText})),c={D:"div",ka:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":b.bq||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",
S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-merchandise-title",U:{dir:g.vn(b.title||"")},ba:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",ba:b.metadata},{D:"a",ka:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:W0(a,b.targetUrl),target:"_blank",tabindex:"-1"},ba:b.callToAction}]}]}]}]},
{D:"div",K:"ytp-ce-expanding-image",U:V0(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",S:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",ba:b.callToAction||void 0}]}]},c=new g.X(c)}b.YL&&g.N(c.element,"ytp-ce-placeholder");return c},V0=function(a){if(a.gD)var b=a.gD.thumbnails;
return GEa(b?b[b.length-1].url:null)},GEa=function(a){return a?{style:"background-image: url("+a+")"}:{}},FEa=function(a,b,c){function d(m){m&&(b.ya("blur",function(){"none"!=m.style.display&&a.W&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.N(b.element,"ytp-ce-force-expand"),X0(a,c.id,!0)):(g.mn(b.element,"ytp-ce-force-expand"),g.mn(b.element,"ytp-ce-element-hover"),X0(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.ya("mouseenter",function(){Y0(a,b,c)});
b.ya("mouseleave",function(){Z0(a,b,c)});
a.player.T().i||b.ya("click",function(){g.N(b.element,"ytp-ce-element-hover")});
b.ya("click",function(m){HEa(a,c,m)});
b.ya("keypress",function(m){HEa(a,c,m)});
b.ya("focus",function(){Y0(a,b,c)});
b.ya("blur",function(){Z0(a,b,c)});
b.ya("touchstart",function(){Y0(a,b,c)});
var l=g.we("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.mn(b.element,"ytp-ce-element-hover");g.mn(b.element,"ytp-ce-force-expand")});
b.ya("keydown",function(m){a.W=9===m.keyCode&&!m.shiftKey});
d(g.we("ytp-sb-subscribe",b.element));d(g.we("ytp-sb-unsubscribe",b.element));b.ya("focus",f);b.ya("blur",h)},HEa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.kn(d,"ytp-ce-element");){g.kn(d,"subscribe-label")&&$0(a,b);
if(g.kn(d,"ytp-ce-channel-subscribe"))return;d=g.Oe(d)}if(!d||g.kn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])Z0(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.CQ)$0(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Lc(W0(a,b.targetUrl)),c=g.Hc(c),g.IJ(c,void 0,b.Cd);else{var e=a.player.getVideoData().C,f=function(){var h=W0(a,b.targetUrl),l=b.Cd,m=g.Bp(h);e&&m&&(m.v||m.list)?a.player.Ai(m.v,l,m.list,!1):g.HJ(h,l)};
$0(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},W0=function(a,b){var c=a.player.T();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.BG(c)+b}else return"";return b},Y0=function(a,b,c){g.kn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.N(b.element,"ytp-ce-element-hover"):a.player.T().i?(new g.M(function(){g.N(b.element,"ytp-ce-element-hover")},200)).start():g.N(b.element,"ytp-ce-element-hover"),a1(a,c.OL),X0(a,c.id,!0))},Z0=function(a,b,c){g.mn(b.element,"ytp-ce-element-hover");
g.mn(b.element,"ytp-ce-force-expand");X0(a,c.id,!1)},X0=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.O(a.i[e].element,"ytp-ce-element-shadow-show",c)},a1=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||T0(a))c&&c();else{b=IEa(a,b);var e=0,f=!1,h=new g.M(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.pq(b[a],d)}},$0=function(a,b,c){a1(a,b.clickUrls,c);
(a=g.iu())&&b.VL&&g.zu(a,b.visualElement)},IEa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(a.Hz(b[e],c));return d},JEa=function(a){return Array.isArray(a)&&a.length?a[0]:a},b1=function(a){return"string"===typeof a?a:""},c1=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},KEa=function(a){this.externalId=a},LEa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},d1=function(a){return a.value?a.value:null},e1=function(a){if(!a)return null;
var b=g.Lc(b1(a.value));b=g.Hc(b);if(!b)return null;var c=c1(a.target,MEa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new LEa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},NEa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},QEa=function(a){if(!a)return null;
var b=c1(a.type,OEa),c=c1(a.trigger,PEa),d=JEa(a.url);d=e1(d?d:null);a=JEa(a.subscribeData);var e=a?a:null;e?(a=b1(e.external_user_id),e=b1(e.subscription_token),a=a&&e?new KEa(a):null):a=null;return b?new NEa(b,c,d,a):null},REa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},TEa=function(a){return(a=SEa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},SEa=function(a,b){return g.cb(a.action,b,void 0)},UEa=function(a,b){this.context=a;
this.i=b},g1=function(a){return a.customMessage?f1("div","iv-card-message",a.customMessage):""},h1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",K:"iv-card-image",U:{style:c},S:d}},i1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(f1("li","",c.value));return{D:"ul",K:"iv-card-meta-info",S:b}},f1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.vn(c);return{D:a,U:b,ba:c}},VEa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Zs&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Zs+");");c.dir=g.vn(a.customMessage);var d=[{D:"span",ba:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",ka:b,U:c,S:d}},j1=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.Cd,c.tracking.click,5)}},WEa=function(a,b){this.merchant=a;
this.price=b},XEa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},YEa=function(a,b){return b?b:XEa(a)?"current":"new"},k1=function(a,b){g.E.call(this);
var c=this;this.element=a;this.context=b;this.La=!1;this.za=new Map;this.Ca=new Map;this.context.G.addEventListener(g.AD("annotations_module"),function(d){(d=c.za.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.BD("annotations_module"),function(d){(d=c.Ca.get(d))&&d.apply(c)})},l1=function(a,b,c,d,e,f,h){a.context.i.ya(b,"click",function(l){a.rw(c,d,e,f||[],h||0,l)});
a.context.i.ya(b,"touchstart",function(){a.La=!1});
a.context.i.ya(b,"touchmove",function(){a.La=!0})},ZEa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},m1=function(a,b,c){return{cE:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
dH:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
lv:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},p1=function(a,b,c){k1.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.la=this.Za=this.u=this.be=!1;this.ca=null;this.cards=[];this.Pa=this.L=this.ga=this.C=this.ma=this.i=null;this.X=[];this.J=this.Td=this.ia=null;this.I=0;this.ea=new g.M(g.Ia,c.B.qd?4E3:3E3);g.I(this,this.ea);this.Ja=new g.M(g.Ia);g.I(this,this.Ja);this.Y=new UEa(c,function(e,f,h,l,m,n){l1(d,e,f,h,l,m,n)});
this.W=new g.X({D:"div",K:"iv-drawer",U:{id:"iv-drawer"},S:[{D:"div",K:"iv-drawer-header",U:{"aria-role":"heading"},S:[{D:"span",K:"iv-drawer-header-text"},{D:"button",ka:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.I(this,this.W);this.B=this.W.element;this.Ha=new g.LL(this.W,330);g.I(this,this.Ha);this.Wa=g.we("iv-drawer-header-text",this.B);this.l=g.we("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Za&&n1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Za=d.u)&&o1(d)})},$Ea=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){n1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){o1(a)});
var d=c.headerText;g.Qe(a.Wa,d);a.L&&a.L.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.ia=g.cu(c.trackingParams);a.J=g.cu(c.closeTrackingParams);a.Td=g.cu(c.iconTrackingParams)},aFa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"simple",teaserText:g.HD(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cd:q1(a,c,b,d),sponsored:!1,tracking:m1(d,e,d.command),Pj:d.trackingParams?g.cu(d.trackingParams):null,Dh:e.trackingParams?
g.cu(e.trackingParams):null,Td:f&&f.trackingParams?g.cu(f.trackingParams):null,imageUrl:r1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.HD(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Zs:null,title:d.title?g.HD(d.title):"",customMessage:d.callToAction?g.HD(d.callToAction):"",url:d.command.urlEndpoint.url?e1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};s1(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"collaborator",teaserText:g.HD(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cd:q1(a,c,b,d),sponsored:!1,tracking:m1(d,e,d.endpoint),Pj:d.trackingParams?g.cu(d.trackingParams):null,Dh:e.trackingParams?g.cu(e.trackingParams):null,Td:f&&f.trackingParams?g.cu(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.HD(d.customText):null,jG:r1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.HD(d.channelName):"",metaInfo:[d.subscriberCountText?g.HD(d.subscriberCountText):""],url:e1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};s1(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"playlist",teaserText:g.HD(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cd:q1(a,c,b,d),sponsored:!1,tracking:m1(d,e,d.action),Pj:d.trackingParams?g.cu(d.trackingParams):null,Dh:e.trackingParams?g.cu(e.trackingParams):null,Td:f&&f.trackingParams?g.cu(f.trackingParams):
null,rs:r1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.HD(d.customMessage):null,playlistVideoCount:g.HD(d.playlistVideoCount),title:d.playlistTitle?g.HD(d.playlistTitle):"",metaInfo:[d.channelName?g.HD(d.channelName):"",d.videoCountText?g.HD(d.videoCountText):""],url:e1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ZEa(d.action)})};s1(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"video",teaserText:g.HD(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cd:q1(a,c,b,d),sponsored:!1,tracking:m1(d,e,d.action),Pj:d.trackingParams?g.cu(d.trackingParams):null,Dh:e.trackingParams?g.cu(e.trackingParams):null,Td:f&&f.trackingParams?g.cu(f.trackingParams):null,rs:r1(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.HD(d.lengthString):null,customMessage:d.customMessage?g.HD(d.customMessage):null,title:d.videoTitle?g.HD(d.videoTitle):"",metaInfo:[d.channelName?g.HD(d.channelName):"",d.viewCountText?g.HD(d.viewCountText):""],isLiveNow:!!d.badge,url:e1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ZEa(d.action)})};s1(a,c)}a.I++},r1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},q1=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},cFa=function(a,b){var c=bFa(a,b);
c&&(c===a.i&&(a.i=null),a.G.removeCueRange(c.card.id),g.Me(c.gx),g.kb(a.cards,c),a.gt(),t1(a))},n1=function(a,b,c){if(!a.u){a.Ha.show();
a.ma=new g.M(function(){g.N(a.context.G.getRootNode(),g.RS.IV_DRAWER_OPEN)},0);
a.ma.start();a.ca=g.Wo(a.l,"mousewheel",function(h){a.ea.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.iu();d&&a.ia&&a.J&&g.xu(d,[a.ia,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.GE||(f.GE=!0,dFa(a.context.logger,f.card.tracking.cE,b)),d&&g.xu(d,[f.card.Pj]);G0(a.G);c&&(a.C=new g.M(function(){a.ga=a.L;a.Pa.focus()},330),a.C.start())}},o1=function(a){a.u&&(a.Ha.hide(),g.Xo(a.ca),a.ca=null,g.mn(a.context.G.getRootNode(),g.RS.IV_DRAWER_OPEN),a.u=!1,G0(a.G),a.C&&a.C.stop(),a.C=new g.M(function(){a.ga&&(a.ga.focus(),a.ga=null)},330),a.C.start())},
fFa=function(a){g.ln(a.element,[g.RS.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.VM(a.G,a.B,5);eFa(a);a.L=g.we("ytp-cards-button",a.G.getRootNode());a.Pa=g.we("iv-drawer-close-button",a.B);a.be=!0},eFa=function(a){var b=g.we("iv-drawer-close-button",a.B);
a.context.i.ya(b,"click",a.FK,a);a.context.i.ya(a.l,"touchend",function(){a.ea.start()});
a.context.i.ya(a.l,"scroll",a.QK,a);a.context.l.subscribe("onHideControls",function(){a.la=!0});
a.context.l.subscribe("onShowControls",function(){a.la=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.la=g.kn(a.G.getRootNode(),"ytp-autohide")});
a.X.push(g.Bo("iv-button-shown",a.dM,a));a.X.push(g.Bo("iv-button-hidden",a.cM,a));a.X.push(g.Bo("iv-teaser-shown",a.iJ,a));a.X.push(g.Bo("iv-teaser-hidden",a.fM,a));a.X.push(g.Bo("iv-teaser-clicked",a.hJ,a))},s1=function(a,b){a.be||fFa(a);
cFa(a,b.id);var c=gFa(a,b);if(c){var d={card:b,gx:c.element,GE:!1},e=hFa(a,d);g.rb(a.cards,e,0,d);c.fa(a.l,e);a.gt();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,t1(a),iFa(a,d),n1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&jFa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){jFa(a,d)}),t1(a))}},gFa=function(a,b){switch(b.type){case "simple":var c=a.Y;
var d=b.displayDomain?{D:"div",K:"iv-card-image-text",ba:b.displayDomain}:void 0;var e=VEa(b);d={D:"div",ka:["iv-card"],S:[{D:"a",K:"iv-click-target",U:{href:b.url?d1(b.url)||"":""},S:[h1(b.imageUrl,d),{D:"div",K:"iv-card-content",S:[f1("h2",void 0,b.title),e]}]}]};d=new g.X(d);j1(c,g.ve("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.Y,d={D:"div",ka:["iv-card","iv-card-channel"],S:[{D:"a",ka:["iv-click-target"],U:{href:d1(b.url)||"","data-ytid":b.channelId},S:[h1(b.jG),
{D:"div",K:"iv-card-content",S:[g1(b),{D:"h2",K:"iv-card-primary-link",ba:b.title},i1(b)]}]}]},d=new g.X(d),j1(c,g.ve("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.Y,d={D:"div",ka:["iv-card","iv-card-playlist"],S:[{D:"a",K:"iv-click-target",U:{href:d1(b.url)||""},S:[h1(b.rs,{D:"div",K:"iv-card-image-overlay",S:[{D:"span",K:"iv-card-playlist-video-count",ba:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",S:[g1(b),f1("h2","iv-card-primary-link",b.title),i1(b)]}]}]},d=new g.X(d),
j1(c,g.ve("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.Y;var f=!g.gb(b.offers);d=["iv-card"];e="";var h=VEa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({D:"div",K:"iv-card-offer-price",ba:h.price}),h.merchant&&f.push({D:"div",K:"iv-card-offer-merchant",ba:h.merchant}),h={D:"div",S:f});f=b.url?d1(b.url)||"":"";d={D:"div",ka:d,U:{tabindex:"0"},S:[{D:"a",ka:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",S:[b.sponsored?{D:"div",K:"iv-card-sponsored",S:["Sponsored",{D:"div",K:"iv-ad-info-container",S:[{D:"div",K:"iv-ad-info",ba:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",S:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",U:{href:f},S:[f1("h2",e,b.title),h]}]}]};d=new g.X(d);e=g.Ie("span");g.Qe(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Ec(e,"adInfo");j1(c,g.ve("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.Y,e=b.videoDuration?{D:"span",K:"iv-card-video-duration",ba:b.videoDuration}:void 0,h=b.isLiveNow?{D:"span",ka:["yt-badge","yt-badge-live"],ba:"LIVE NOW"}:null,e={D:"div",ka:["iv-card","iv-card-video"],S:[{D:"a",K:"iv-click-target",U:{href:(null===(d=b.url)||void 0===d?void 0:d1(d))||""},S:[h1(b.rs,e),{D:"div",K:"iv-card-content",S:[g1(b),f1("h2","iv-card-primary-link",b.title),i1(b),h]}]}]},d=new g.X(e),
j1(c,g.ve("iv-click-target",d.element),b,b.url),d;default:return null}},hFa=function(a,b){if(0===a.cards.length)return 0;
var c=g.db(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},kFa=function(a){return a.i?"productListing"===a.i.card.type:g.fh(a.cards,function(b){return"productListing"===b.card.type})},t1=function(a){g.O(a.G.getRootNode(),"ytp-cards-shopping-active",kFa(a))},jFa=function(a,b){if(!g.kn(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.iu(),d=a.i?a.i.card.Td:a.Td;
c&&d&&g.yu(c,[d]);a.i=b;t1(a)}if(c="none"!=a.element.style.display)g.U(a.context.G.T().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.G.getPresentingPlayerType()?(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.G.getAdState();c&&b.card.teaserDurationMs&&a.G.rp(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ja.isActive()||((!a.u||!a.ea.isActive()&&a.la)&&iFa(a,b),a.Ja.start(910+b.card.teaserDurationMs))}},
iFa=function(a,b){if(a.W.ab){var c=new L0([0,
a.l.scrollTop],[0,b.gx.offsetTop],600,uEa);a.context.u.ya(c,"animate",function(d){a.l.scrollTop=d.y});
a.context.u.ya(c,"finish",function(d){a.l.scrollTop=d.y});
c.play()}else g.YK(a.W,!0),a.l.scrollTop=b.gx.offsetTop,g.YK(a.W,!1)},u1=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},bFa=function(a,b){return g.cb(a.cards,function(c){return c.card.id===b})},v1=function(a,b,c){k1.call(this,a,b);
this.annotation=c;this.isActive=!1},lFa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},w1=function(a,b,c){v1.call(this,a,b,c);
this.l=null;this.J=!1;this.u=null;this.B=!1;this.i=this.I=this.C=null},mFa=function(a,b){var c=void 0===c?0:c;
var d=sEa(b).width;g.ug(b,d);c=new N0(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,tEa);g.I(a,c);a.context.u.ya(c,"begin",function(){g.Fg(b,!0)});
c.play()},pFa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
ka:["iv-branding-context-name"],ba:b.channel_name}),d=a.createElement({D:"div",ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.fO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.G),a.i.fa(d));var f=a.createElement({D:"div",ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",ka:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Fg(h,!1);var l=a.createElement({D:"div",ka:["branding-context-container-outer"]});l.appendChild(h);g.mg(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.M(function(){nFa(a,h,l)},500);
g.I(a,a.u);a.context.i.ya(a.element,"mouseover",function(){oFa(a,h,l,f,b.image_height)});
a.context.i.ya(a.element,"mouseout",function(){a.u.start()})}},oFa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.Eg(b);a.i||(b.style.width=g.tg(f.width,!0),c.style.width=g.tg(f.width,!0));g.mg(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.mg(d,"right","1px");a.B=!0;g.Fg(b,!0);a.C=new g.M(function(){g.N(this.element,"iv-branding-active")},0,a);
a.C.start()}},nFa=function(a,b,c){g.mn(a.element,"iv-branding-active");
a.I=new g.M(function(){g.Fg(b,!1);a.i||(c.style.width=g.tg(0,!0))},250);
a.I.start();a.B=!1},qFa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.B=c;this.videoData=d;this.logger=e;this.G=f;this.l=h},x1=function(a,b,c){v1.call(this,a,b,c);
var d=this;this.L=this.isCollapsed=this.W=!1;this.I=5E3;this.l=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",ka:["iv-promo-contents"]});this.C=new g.M(function(){d.i.setAttribute("aria-hidden","true");g.Fg(d.u,!1);g.Fg(d.l,!0)},700,this);
g.I(this,this.C)},rFa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=TEa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",ka:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",U:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",ba:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",ba:b.playlist_length.toString()}),h.appendChild(f));e&&l1(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.md(f,d1(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",S:[{D:"strong",
ba:b.text_line_1}]});var m=a.createElement({D:"p",S:[{D:"span",K:"iv-promo-link",ba:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",ka:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",ka:["iv-button","iv-promo-button"],S:[{D:"span",K:"iv-button-content",ba:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&l1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.N(a.i,
"iv-click-target");e&&l1(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",S:[{D:"span",ba:b.text_line_1}]}),m=a.createElement({D:"p",S:[{D:"strong",ba:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",ka:["yt-badge","iv-promo-badge-live"],ba:"LIVE NOW"})),g.N(a.i,"iv-click-target"),e&&l1(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);p&&
a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.l=a.createElement({D:"button",ka:["iv-promo-expand","ytp-button"]});a.l.title="Expand";a.context.i.ya(a.l,"click",function(r){y1(a,5E3,r)});
c.appendChild(a.l);g.Fg(a.l,!1);a.context.i.ya(a.element,"mouseover",a.xL,a);a.context.i.ya(a.element,"mouseout",a.wL,a);a.context.i.ya(a.element,"touchend",function(r){y1(a,5E3,r)});
a.u=a.createElement({D:"button",ka:["iv-promo-close","ytp-button"]});a.u.title="Close";a.context.i.ya(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.rL:a.qL,a);c.appendChild(a.u);g.ln(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},y1=function(a,b,c){c.stopPropagation();
sFa(a);tFa(a,b);a.i.focus()},uFa=function(a){a.isCollapsed||a.L||a.B||(g.N(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},sFa=function(a){a.C.stop();
a.isCollapsed&&(g.nn(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Fg(a.l,!1),g.Fg(a.u,!0))},tFa=function(a,b){a.B||(a.B=g.Gm(function(){z1(this);
uFa(this)},b,a))},z1=function(a){a.B&&(g.A.clearTimeout(a.B),a.B=null)},vFa=function(a){this.G=a},dFa=function(a,b,c){b&&(c?A1(a,b.map(function(d){return g.$m(d,c)})):A1(a,b))},A1=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.pq(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},B1=function(a){g.eN.call(this,a);
var b=this;this.W=!1;this.loadNumber=0;this.J={};this.logger=new vFa(this.player);this.C=new g.XM(this);this.I=this.u=null;this.events=new g.XM(this);this.L=this.i=null;this.X=[];g.I(this,this.C);this.C.N(this.player,"onVideoAreaChange",function(){b.V("onVideoAreaChange")});
this.C.N(this.player,"onHideControls",function(){b.V("onHideControls")});
this.C.N(this.player,"onShowControls",function(){b.V("onShowControls")});
this.C.N(this.player,"resize",function(d){b.V("resize",d)});
this.C.N(this.player,"presentingplayerstatechange",function(d){b.V("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.jJ,this);this.subscribe("resize",this.Iu,this);this.player.T().L.subscribe("vast_info_card_add",this.YF,this);g.I(this,this.events);this.Y=this.createElement({D:"div",K:"video-custom-annotations"});this.l=new g.X({D:"div",ka:["ytp-player-content","ytp-iv-player-content"]});g.I(this,this.l);g.VM(this.player,this.l.element,4);this.l.hide();this.B=new g.X({D:"div",ka:["ytp-iv-video-content"]});g.I(this,this.B);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.Hn()&&this.load();var c=this.createElement({D:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.Gi(this,function(){g.Me(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},wFa=function(a){a=a.createElement({D:"div",
ka:["annotation","annotation-type-custom"]});g.Fg(a,!1);return a},xFa=function(a,b){var c=!b.isCued()&&!g.W(b,1024);
g.YK(a.l,c);g.YK(a.B,c)},yFa=function(a,b,c){a.W=!0;
a.I=g.Tp(b,c)},zFa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(zFa(a,e))}return c},CFa=function(a){var b=a.player.getVideoData();
if(b.ca){var c=a.player.T().L.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Np(h)&&h.responseXML?h.responseXML:null)&&C1(a,h)}};
g.mp()&&(d.onFinish=AFa(a,d.onFinish));d.postParams={ic_only:"1"};BFa(d,c);a.W=!0;g.Tp(b.ca,d)}}},BFa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.mq&&(a.postParams.ic_coll=b.mq);b.kt&&(a.postParams.ic_xml=b.kt);b.ws&&(a.postParams.ic_track=b.ws)},DFa=function(a){var b=new g.X({D:"div"});
g.Fg(b.element,!1);var c=new p1(a.player,b.element,D1(a));g.I(c,b);b.fa(a.l.element);c.Vr();return c},D1=function(a){if(!a.L){var b=new O0(a);
g.I(a,b);var c=new g.w_(a);g.I(a,c);a.L=new qFa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.qd)}return a.L},C1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.iu();if(e){var f=g.gu();f&&g.ou(g.Ko("use_default_events_client")?void 0:g.$s,e,f,[g.cu(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=zFa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=c1(h.type,EFa),r=c1(h.style,FFa),t=b1(h.data),w=0!==t.length?JSON.parse(t):{};var x=h.action;h=QEa;if(null==x)var y=null;else if(g.Ma(x)){m=[];for(var F=g.q(x),D=F.next();!D.done;D=
F.next()){var G=h(D.value);G&&m.push(G)}y=m}else{var K=h(x);y=K?[K]:[]}f=n&&p?new REa(n,p,r,y,w):null}else f=null}catch(wa){}if(f)if("branding"===f.type||"promotion"===f.type){h=a;m=f;var J=wFa(h),H=null;switch(m.type){case "branding":if(h.player.T().Db)break;h.l.element.appendChild(J);H=new w1(J,D1(h),m);break;case "promotion":g.VM(h.player,J,4),H=new x1(J,D1(h),m)}H&&H.Vr();if(h=H)g.I(a,h),a.J[f.id]=h}else if("card"===f.type||"drawer"===f.type){a.i||(a.i=DFa(a),g.I(a,a.i));if("card"===f.type){c=
a.i;var L=f&&f.data&&f.data.card_type;h=f.data;if(L)switch(m=h.tracking||{},m={cE:m.impression,click:m.click,close:m.close,dH:m.teaser_impression,lv:m.teaser_click},J=h.tracking_params||{},H=null,L){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cd:h.session_data||{},sponsored:h.sponsored||!1,tracking:m,Pj:J.card?g.cu(J.card):null,Dh:J.teaser?g.cu(J.teaser):null,Td:J.icon?
g.cu(J.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,jG:h.image_url,title:h.title,metaInfo:h.meta_info,url:e1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};s1(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cd:h.session_data||{},sponsored:h.sponsored||!1,tracking:m,Pj:J.card?g.cu(J.card):
null,Dh:J.teaser?g.cu(J.teaser):null,Td:J.icon?g.cu(J.icon):null,rs:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:e1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};s1(c,f);break;case "productListing":h.signin_url&&(H=e1({target:"current",value:h.signin_url}));L=[];for(var T=h.offers||[],na=0;na<T.length;na++)L.push(new WEa(g.td(T[na].merchant),g.td(T[na].price)));f=
{id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cd:h.session_data||{},sponsored:h.sponsored||!1,tracking:m,Pj:J.card?g.cu(J.card):null,Dh:J.teaser?g.cu(J.teaser):null,Td:J.icon?g.cu(J.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,Zs:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:
null,url:e1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),X3:H,W3:h.signin_title?h.signin_title:void 0,V3:h.signin_message?h.signin_message:void 0,offers:L};s1(c,f);break;case "simple":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cd:h.session_data||{},sponsored:h.sponsored||!1,tracking:m,Pj:J.card?g.cu(J.card):null,Dh:J.teaser?g.cu(J.teaser):null,Td:J.icon?
g.cu(J.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,Zs:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:e1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};s1(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||
!1,Cd:h.session_data||{},sponsored:h.sponsored||!1,tracking:m,Pj:J.card?g.cu(J.card):null,Dh:J.teaser?g.cu(J.teaser):null,Td:J.icon?g.cu(J.icon):null,rs:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:e1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},s1(c,f)}}else $Ea(a.i,f);c=!0}}c&&(G0(a.player),a.Iu())},GFa=function(a,b){var c=!1;
a.i||(a.i=DFa(a),g.I(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(aFa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.HD(b.headerText):"",g.Qe(c.Wa,d),c.L&&c.L.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.ia=b.trackingParams?g.cu(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.cu(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Td=b.icon.infoCardIconRenderer.trackingParams?
g.cu(b.icon.infoCardIconRenderer.trackingParams):null,G0(a.player),a.Iu())},HFa=function(a,b,c,d,e){if(!a.player.T().Db){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new NEa("openUrl","click",new LEa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.HD(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.HD(b.subscriberCountText))):(b.subscriberCountText&&(e=g.HD(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.HD(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.HD(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.HD(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new REa(c,"branding","branding",f,d);l=wFa(a);a.l.element.appendChild(l);f=new w1(l,D1(a),f);f.Vr();g.I(f,f);a.J[c]=f}},AFa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.na()||(d.unshift(b),b=g.Qa.apply(window,d),a.X.push(g.kp(b)))}},IFa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.OM.prototype.rp=g.ca(15,function(a,b){var c=g.pN(this.Ua());c&&c.rp(a,b)});
var I0={},J0=null;g.Ta(L0,g.pn);g.k=L0.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Ma)this.progress=0,this.coords=this.i;else if(this.Kb())return!1;K0(this);this.startTime=a=g.Sa();-1==this.Ma&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.Hu();this.lh("play");-1==this.Ma&&this.lh("resume");this.Ma=1;var b=g.Pa(this);b in I0||(I0[b]=this);wEa();xEa(this,a);return!0};
g.k.stop=function(a){K0(this);this.Ma=0;a&&(this.progress=1);yEa(this,this.progress);this.lh("stop");this.Cr()};
g.k.pause=function(){this.Kb()&&(K0(this),this.Ma=-1,this.lh("pause"))};
g.k.da=function(){0==this.Ma||this.stop(!1);this.lh("destroy");L0.Ed.da.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.qw=function(){this.lh("animate")};
g.k.lh=function(a){this.dispatchEvent(new zEa(a,this))};
g.Ta(zEa,g.Cl);g.Ta(M0,L0);M0.prototype.u=g.Ia;M0.prototype.qw=function(){this.u();M0.Ed.qw.call(this)};
M0.prototype.Cr=function(){this.u();M0.Ed.Cr.call(this)};
M0.prototype.Hu=function(){this.u();M0.Ed.Hu.call(this)};
g.Ta(N0,M0);N0.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.u(O0,g.E);O0.prototype.ya=function(a,b,c,d){c=(0,g.B)(c,d||this.l);a=g.Wo(a,b,c);this.i.push(a);return a};
O0.prototype.Uy=function(a,b,c,d){c=(0,g.B)(c,d||this.l);a=g.ep(a,b,c);this.i.push(a);return a};
O0.prototype.Gb=function(a){g.Xo(a);g.kb(this.i,a)};
O0.prototype.da=function(){g.Xo(this.i);this.i.length=0;g.E.prototype.da.call(this)};g.u(S0,g.eN);g.k=S0.prototype;g.k.load=function(){g.eN.prototype.load.call(this);if(!T0(this)){var a=g.Jia(this.player.getVideoData());a?(a=R0(a,BEa(this)),U0(this,a,!1)):CEa(this)}};
g.k.unload=function(){U0(this,null);this.u&&(this.u.abort(),this.u=null);g.eN.prototype.unload.call(this)};
g.k.Fe=function(a,b){if(!T0(this))return null;if("loadCustomEndscreenRenderer"===a){var c=R0(b,"new");U0(this,c);return!0}return null};
g.k.getOptions=function(){return T0(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Ta=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<JFa.length;f++){var h=Math.abs(b.width-JFa[f]);if(-1===e||d>=h)e=f,d=h}d=KFa[e];this.l&&g.mg(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Dg(e.element,Math.round(h.width*a.width),f);g.ug(e.element,m,n);g.nn(e.element,LFa);m=h.left+h.width/2;h=h.top+l/2;g.N(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.nn(e.element,KFa);g.N(e.element,d);(e=g.se(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.mg(e,"height",f+"px")}}}}};
g.k.zd=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())a1(this,this.endscreen.impressionUrls),(a=g.iu())&&this.endscreen.visualElement&&g.pu(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.N(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.N(b,"ytp-ce-shown");a1(this,c.impressionUrls);(b=g.iu())&&g.pu(b,c.visualElement,void 0);this.player.T().u&&this.player.xa("endscreenelementshown",
a)}};
g.k.mf=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.mn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.mn(b,"ytp-ce-shown");this.player.T().u&&this.player.xa("endscreenelementhidden",a)}};
g.k.DP=function(a){var b=this;a.target===window&&(new g.M(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.nn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.Hz=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})};
var JFa=[346,426,470,506,570,640,853,1280,1920],KFa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),LFa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var MEa={BU:"current",a_:"new"};var OEa={CLOSE:"close",m_:"openUrl",kK:"subscribe"},PEa={tS:"click",CLOSE:"close",VV:"hidden",u0:"rollOut",v0:"rollOver",e1:"shown"};var FFa={PR:"anchored",LH:"branding",CHANNEL:"channel",zU:"cta",YV:"highlightText",XW:"label",PLAYLIST:"playlist",R_:"popup",o1:"speech",kK:"subscribe",I1:"title",VIDEO:"video",R2:"website"},EFa={LH:"branding",iS:"card",PU:"drawer",XV:"highlight",wY:"marker",Z_:"promotion",TEXT:"text",X2:"widget"};g.u(k1,g.E);g.k=k1.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.xD(a,b,{id:c});a.namespace="annotations_module";d&&this.za.set(a,d);e&&this.Ca.set(a,e);this.context.G.sd([a])};
g.k.Vr=function(){this.context.l.subscribe("resize",this.gt,this)};
g.k.rw=function(a,b,c,d,e,f){if(this.La)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Me(this.element)};
g.k.gt=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=d1(a);if(f){var h=YEa(f,a.target),l=function(){a.i&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.Bp(f||"");m&&n&&(n.v||n.list)?e.context.G.Ai(n.v,b,n.list,!1):g.IJ(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);A1(this.context.logger,c,l,d);XEa(f)||(c=g.iu(),d=b.itct,c&&d&&g.zu(c,g.cu(d)))}};
g.k.da=function(){this.za.clear();this.Ca.clear();g.E.prototype.da.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.I(this,a);return a.element};g.u(p1,k1);g.k=p1.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Eg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.gt=function(){var a=this.isAvailable();g.Fg(this.element,a);g.O(this.context.G.getRootNode(),g.RS.IV_DRAWER_ENABLED,a);G0(this.G)};
g.k.destroy=function(){this.G.rp(!1);try{this.G.getRootNode().removeChild(this.B)}catch(a){}g.Co(this.X);g.Xo(this.ca);this.ma&&this.ma.dispose();this.C&&this.C.dispose();k1.prototype.destroy.call(this)};
g.k.FK=function(){if(this.u){A1(this.context.logger,u1(this).tracking.close);var a=g.iu();a&&this.J&&g.zu(a,this.J);o1(this)}};
g.k.QK=function(){g.O(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.dM=function(){var a=g.iu(),b=u1(this);b=b?b.Td:this.Td;a&&b&&g.xu(a,[b])};
g.k.cM=function(){var a=g.iu(),b=u1(this);b=b?b.Td:this.Td;a&&b&&g.yu(a,[b])};
g.k.iJ=function(){var a=u1(this);A1(this.context.logger,a.tracking.dH);var b=g.iu();b&&a&&g.xu(b,[a.Dh,a.Td])};
g.k.fM=function(){var a=g.iu(),b=u1(this);a&&b&&g.yu(a,[b.Dh])};
g.k.hJ=function(a){var b=u1(this),c=g.iu();this.i?a?(a=this.context.logger,A1(a,b.tracking.lv),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Dh&&g.zu(c,b.Dh)):(a=this.context.logger,A1(a,b.tracking.lv),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Td&&g.zu(c,b.Td)):(a=this.context.logger,A1(a,b.tracking.lv),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Td&&g.zu(c,this.Td))};g.u(v1,k1);v1.prototype.Vr=function(){k1.prototype.Vr.call(this);lFa(this)};
v1.prototype.show=function(){k1.prototype.show.call(this);var a=g.iu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.xu(a,[g.cu(b.itct)])};
v1.prototype.hide=function(){k1.prototype.hide.call(this);var a=g.iu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.yu(a,[g.cu(b.itct)])};g.u(w1,v1);
w1.prototype.show=function(){if(!this.isActive){v1.prototype.show.call(this);if(!this.J){g.N(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",ka:["branding-img","iv-click-target"],U:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Fg(this.l,!1);var b=this.createElement({D:"div",ka:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=TEa(this.annotation))&&l1(this,this.l,b,this.annotation.id,
a.session_data);pFa(this,a);this.J=!0}g.Fg(this.element,!0);this.isActive=!0;this.l&&mFa(this,this.l)}};
w1.prototype.hide=function(){this.isActive&&(v1.prototype.hide.call(this),g.Fg(this.element,!1),this.isActive=!1)};
w1.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);v1.prototype.destroy.call(this)};g.u(x1,v1);g.k=x1.prototype;g.k.show=function(){this.isActive||(v1.prototype.show.call(this),this.W||(rFa(this),this.W=!0),g.Fg(this.element,!0),g.Gm(function(){g.mn(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,z1(this),sFa(this),tFa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.N(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.rw=function(a,b,c,d,e,f){return this.isCollapsed?!1:v1.prototype.rw.call(this,a,b,c,d,e,f)};
g.k.xL=function(a){this.L=!0;y1(this,500,a)};
g.k.wL=function(){this.L=!1;uFa(this)};
g.k.qL=function(a){a.stopPropagation();this.hide()};
g.k.rL=function(a){a.stopPropagation();z1(this);this.isCollapsed=!0;g.N(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();v1.prototype.destroy.call(this)};g.u(B1,g.eN);g.k=B1.prototype;g.k.Fe=function(a,b){if(!IFa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.v_(b);c&&C1(this,c);return!0;case "removeCustomAnnotationById":return b&&this.i&&(cFa(this.i,b),G0(this.player)),!0}return null};
g.k.getOptions=function(){return IFa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Hn=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.WE||a.L.get(b.videoId)||g.hI(b)||g.iI(b)?!0:!1};
g.k.Iu=function(){if(this.B){var a=this.player.Ka().getVideoContentRect(!0);g.Dg(this.B.element,a.width,a.height);g.ug(this.B.element,a.left,a.top)}if(this.i){var b=this.player.Vi();a=this.i;b=b.width;g.O(a.B,"iv-drawer-small",426>=b);g.O(a.B,"iv-drawer-big",1280<=b)}};
g.k.jJ=function(a){xFa(this,a.state);g.W(a.state,2)&&(this.Hg()&&this.Ii()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.rp(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.I=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Np(h)&&h.responseXML?h.responseXML:null)&&(C1(b,h),g.N(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.eN.prototype.load.call(this);xFa(this,this.player.Xa());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.mp()&&(a=AFa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.I=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().L.get(d);f&&BFa(e,f);f=f&&(f.kt||f.mq);if(!c.Dk||f)c.ca?yFa(this,c.ca,e):(this.u=function(){b.Oa(e)},this.player.addEventListener("videodatachange",this.u));
g.VM(this.player,this.B.element,4);this.Iu();(f=g.hI(c))&&GFa(this,f);(f=g.iI(c))&&f.featuredChannel&&HFa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.Oa=function(a){var b=this.player.getVideoData();b.ca&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),yFa(this,b.ca,a))};
g.k.unload=function(){this.player.Oe("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.L=null;this.i&&(this.i.destroy(),this.i=null,G0(this.player));this.W=!1;this.I&&(this.I.abort(),this.I=null);this.J={};this.l.hide();g.eN.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.YF=function(a){a===this.player.getVideoData().videoId&&(this.loaded?CFa(this):this.load())};
g.k.Hg=function(){return!!this.i&&this.i.isAvailable()};
g.k.Ii=function(){this.Hg();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Hg();this.i&&(a?c?n1(this.i,c,b):n1(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):o1(this.i))};
g.k.rp=function(a,b){this.player.V(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.da=function(){this.player.T().L.unsubscribe("vast_info_card_add",this.YF,this);g.mn(this.player.getRootNode(),g.RS.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.np(a[b]);this.X.length=0;g.eN.prototype.da.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.I(this,a);return a.element};g.kN.annotations_module=B1;g.kN.creatorendscreen=S0;})(_yt_player);
